name: Java CI/CD with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: IMANE

    steps:
      - uses: actions/checkout@v4

      - name: Debug Repository Structure
        run: |
          echo "Current directory:"
          pwd
          echo "Repository structure:"
          tree -L 3
          echo "Searching for pom.xml files:"
          find . -name pom.xml

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          pom_file=$(find . -name pom.xml | head -n 1)
          if [ -z "$pom_file" ]; then
            echo "No pom.xml found"
            exit 1
          else
            echo "Found pom.xml at: $pom_file"
            echo "Building project..."
            mvn -f "$pom_file" clean install
          fi

      - name: Docker deploy
        run: |
          pwd
          cd deploy
          docker compose up -d