name: Java CI/CD with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Debug information
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -R
          echo "Git status:"
          git status

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          cd backend-ms1
          mvn clean install

    # Comment out other steps for now
    # - name: Run Unit Tests with Maven
    #   run: mvn -f backend-ms1/pom.xml test

    # - name: Run Integration Tests with Maven Using Karate
    #   run: mvn -f backend-ms1/pom.xml verify -Dtest=RunKarateTests

    # - name: Run Integration Quality with Sonar
    #   run: mvn -f backend-ms1/pom.xml sonar:sonar

    # - name: Build Docker image
    #   run: docker build -t your-image-name:${{ github.sha }} backend-ms1