name: Java CI/CD with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Debug information
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -R
          echo "Git status:"
          git status
          echo "Git branch:"
          git branch -a

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Find pom.xml
        run: |
          pom_file=$(find . -name pom.xml)
          if [ -z "$pom_file" ]; then
            echo "No pom.xml found"
            exit 1
          else
            echo "Found pom.xml at: $pom_file"
            echo "POM_FILE=$pom_file" >> $GITHUB_ENV
          fi

      - name: Build with Maven
        if: env.POM_FILE
        run: |
          cd $(dirname $POM_FILE)
          mvn clean install

    # Other steps are commented out for now