name: Java CI/CD with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: IMANE

    steps:
      - uses: actions/checkout@v4


      - name: Docker deploy
        run: |
          pwd
