name: Java CI/CD with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Change to backend-ms1 directory
        run: cd backend-ms1

      - name: Compile with Maven
        run: mvn -f backend-ms1/pom.xml compile

      - name: Run Unit Tests with Maven
        run: mvn -f backend-ms1/pom.xml test

      - name: Run Integration Tests with Maven Using Karate
        run: mvn -f backend-ms1/pom.xml verify -Dtest=RunKarateTests

      - name: Run Integration Quality with Sonar
        run: mvn -f backend-ms1/pom.xml sonar:sonar
        # Note: You'll need to configure Sonar separately and add necessary secrets

      - name: Run Package with Maven
        run: mvn -f backend-ms1/pom.xml package -DskipTests

      - name: Build Docker image
        run: docker build -t your-image-name:${{ github.sha }} backend-ms1

    # Add deployment steps here if needed