name: Java CI/CD Debugging

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Information
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents (root):"
          ls -la
          echo "All files and directories (including hidden):"
          find . -maxdepth 3 -print
          echo "Git status:"
          git status
          echo "Git branch:"
          git branch -a
          echo "Searching for pom.xml:"
          find . -name pom.xml

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Attempt Maven Build
        run: |
          pom_file=$(find . -name pom.xml | head -n 1)
          if [ -z "$pom_file" ]; then
            echo "No pom.xml found"
            exit 1
          else
            echo "Found pom.xml at: $pom_file"
            echo "Attempting to build..."
            mvn -f "$pom_file" clean install
          fi