version: '3'

services:

#  front-end:
#    build: ../frontend
#    container_name: frontend
#    ports:
#      - "${FRONT_END_PORT}:80"
#    expose:
#      - "${FRONT_END_PORT}"
#    networks:
#      - app-network

  zyn-service-db:
    image: ${ZYN_SERVICE_DB_IMAGE_NAME}
    container_name: ${ZYN_SERVICE_DB_CONTAINER_NAME}
    volumes:
      - app-data:/var/lib/mysql
    ports:
      - "${ZYN_SERVICE_DB_PORT}:${ZYN_SERVICE_DB_PORT}"
    environment:
      - MYSQL_DATABASE=${ZYN_SERVICE_DB_NAME}
      - MYSQL_USER=${ZYN_SERVICE_DB_USER}
      - MYSQL_PASSWORD=${ZYN_SERVICE_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${ZYN_SERVICE_DB_PASSWORD_ROOT}
    networks:
      - app-network

  zyn-service-back:
    build: 
      context: ${ZYN_SERVICE_PROJECT_PATH}
      dockerfile: DockerfileWithPackage
    container_name: ${ZYN_SERVICE_CONTAINER_NAME}
    image: ${ZYN_SERVICE_IMAGE_NAME}
    ports:
      - "${ZYN_SERVICE_BACK_PORT}:${ZYN_SERVICE_BACK_PORT}"
    environment:
      - ZYN_SERVICE_DB_URL=${ZYN_SERVICE_DB_URL}
      - ZYN_SERVICE_DB_USER=${ZYN_SERVICE_DB_USER}
      - ZYN_SERVICE_DB_PASSWORD=${ZYN_SERVICE_DB_PASSWORD}
    depends_on:
      - zyn-service-db
    networks:
      - app-network

  minio:
    image: ${MINIO_IMAGE_NAME}
    container_name: ${MINIO_CONTAINER_NAME}
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./data/minio_data:/data
    ports:
      - "${MINIO_HOME_PORT}:9000"
      - "${MINIO_URL_PORT}:9001"
    networks:
      - app-network

volumes:
  app-data:

networks:
  app-network: