name: Java CI with Maven and Angular

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile with Maven
        run: mvn compile
        working-directory: backend-ms1

  test-backend:
    runs-on: ubuntu-latest
    needs: compile-backend  # Wait for compile job to finish

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Need to check out code again in a new job environmentoij

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Unit Tests with Maven
        run: mvn test
        working-directory: backend-ms1

      - name: Run Package with Maven
        run: mvn clean package -DskipTests
        working-directory: backend-ms1

  build-backend:
    runs-on: ubuntu-latest
    needs: test-backend  # Wait for compile job to finish
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Package with Maven
        run: mvn clean package -DskipTests
        working-directory: backend-ms1

  setting-up-NodeModule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout code to the environment

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

  build-frontend:
    runs-on: ubuntu-latest
    needs: setting-up-NodeModule  # This ensures that build-frontend waits for setting-up-NodeModule to finish
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout code again in this job

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Same Node.js version for consistency

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build


