
name: Java CI with Maven and Angular

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'


  test:
    runs-on: ubuntu-latest
    steps:

      - name: Compile with Maven
        run: mvn compile
        working-directory: backend-ms1

      - name: Run Unit Tests with Maven
        run: mvn test
        working-directory: backend-ms1

      - name: Run Package with Maven
        run: mvn clean package -DskipTests
        working-directory: backend-ms1
