name: Java CI with Maven and Angular

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: backend-ms1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker-in-Docker
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=docker:dind
          
      - name: Wait for Docker to stabilize
        run: |
          timeout=60
          until docker info >/dev/null 2>&1 || [ $timeout -eq 0 ]; do
            sleep 1
            ((timeout--))
          done
          if [ $timeout -eq 0 ]; then
            echo "Docker failed to start within the allocated time."
            exit 1
          fi
          
      - name: Debug Docker
        run: |
          docker version
          docker info
          docker ps -a
          
      - name: Run Deploy with Docker
        run: |
          docker context create dind
          docker context use dind
          docker compose version
          docker compose config
          docker compose up -d
        working-directory: deploy

      - name: Check container status
        if: failure()
        run: |
          docker ps -a
          docker logs $(docker ps -aq)
        working-directory: deploy
