name: Java CI with Maven and Angular

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Backend Steps
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compile with Maven
        run: mvn compile
        working-directory: backend-ms1

      - name: Run Unit Tests with Maven
        run: mvn test
        working-directory: backend-ms1

      - name: Run Package with Maven
        run: mvn clean package
        working-directory: backend-ms1

      # Frontend Steps
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Upload frontend build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-dist
          path: frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download frontend build artifacts
        uses: actions/download-artifact@v3
        with:
          name: frontend-dist

      - name: Setup Nginx
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx
          sudo rm -rf /usr/share/nginx/html/*
          sudo cp -r frontend/* /usr/share/nginx/html/
          sudo cp frontend/default.conf /etc/nginx/conf.d/default.conf

      - name: Start Nginx
        run: sudo systemctl start nginx

      - name: Run Deploy with Docker
        run: docker compose up -d
        working-directory: deploy
