name: Docker Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -DskipTests
      working-directory: backend-ms1

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: backend-ms1/target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: app
        path: deploy

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Deploy application
      run: |
        echo "Deploying application..."
        cd deploy
        docker compose up -d --build
