name: Java CI with Maven and Angular

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Compile with Maven
      run: mvn compile
      working-directory: backend-ms1

    - name: Run Unit Tests with Maven
      run: mvn test
      working-directory: backend-ms1
      
    - name: Run Package with Maven
      run: mvn clean package -DskipTests
      working-directory: backend-ms1

   
   # Frontend Steps
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
          node-version: '16'

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Build frontend
      run: |
        cd frontend
        npm run build

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
  
  

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download frontend build artifacts
      uses: actions/download-artifact@v3
      with:
        name: frontend-dist
        path: frontend-build



    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup Nginx
      run: |
        sudo apt-get update
        sudo apt-get install -y nginx
        sudo rm -rf /usr/share/nginx/html/*
        sudo cp -r frontend-build/* /usr/share/nginx/html/
        sudo cp frontend-build/default.conf /etc/nginx/conf.d/default.conf
    

    - name: Deploy application
      run: |
        echo "Deploying application..."
        cd deploy
        docker compose up -d --build
