name: Java CI with Maven and Angular

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build with Maven
        run: mvn clean package -DskipTests -Dspring-boot.build-image.skip=true
        working-directory: backend-ms1

      - name: Build Docker image
        run: |
          docker build -t my-app:latest .
        working-directory: backend-ms1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Debug Docker
        run: |
          docker version
          docker info
          docker ps -a
          
      - name: Run Deploy with Docker
        run: |
          docker compose version
          docker compose config
          docker compose up -d
        working-directory: deploy

      - name: Check container status
        if: always()
        run: |
          docker ps -a
          for container in $(docker ps -aq); do
            echo "Logs for container $container:"
            docker logs $container
          done
        working-directory: deploy
